### PR TITLE
create callback-based DataLoader + example File/Memory loaders

### PR DESCRIPTION
**Pull request by jprjr**
Hey, this is a concept I played around with today based on #18 discussion.

I refactored FileLoader into a more generic DataLoader class. I renamed a few fields to make them less verbose/less redundant (FileLoader_GetFileSize => DataLoader_GetSize), and then created FileLoader and MemoryLoader implementations. The MemoryLoader features in-memory gzip decoding,too.

There's a few callback functions that aren't actually used anywhere just yet, I just figured they'd be really useful for future goals, like playing while still loading.

### CODE REVIEW

**Comment by jprjr** [comment]
There's probably a bit to be desired for that "fopen"-type function. Right now in the memory loader, I'm using the UINT8 pointer as an initial "context", then I pass a pointer to the memory size in the `fopen` callback.

I think it might be easier/make more sense to make that "Init" function just handle linking up the callbacks, and change the Load function to take a variable number of void * arguments, and each module would be responsible for converting them to the appropriate data types.

**Comment by ValleyBell** [comment]
Looks good so far. There are only 2 things that bother me:
- the variable argument list in the Load function  
  I don't think that this is a nice interface. I would rather have functions where it is clear what parameters you pass.
- Your loaders now have "New", "Delete" and "Init". Can you please reduce this to just two functions?  
  In the other classes in the utils folder I used "Init"/"Deinit" as constructor/destructor. It might be a good idea to just use those names.

**Comment by jprjr** [comment]
Can do! I'll try to come up with a nicer interface for the Load function. Maybe it just shouldn't take any parameters? Like the user should come up with a struct that captures whatever parameters they need, and their `dopen` function should just rely on whatever's in the context pointer. Then the `Init` method could accept a context pointer alongside the callbacks pointer.

**Comment by jprjr** [comment]
Just pushed up some changes, let me know if you'd like them squashed into a single commit.

Now the interface is something like:

```
DATA_LOADER *fLoader = FileLoader_Init(char *filename);
DATA_LOADER *mLoader = MemoryLoader_Init(UINT8 *buffer, UINT32 length);
```

Those init functions take care of allocating the DATA_LOADER, setup the private `context` object, etc. When the user is done, they call the appropriate Deinit function (`FileLoader_Deinint`, `MemoryLoader_Deinit`).

I also used defines to create aliases to the DataLoader functions, so a user can keep using that `FileLoader` prefix, ie: `FileLoader_SetPreloadBytes(0x100)`.

**Comment by jprjr** [comment]
As soon as I typed that comment, I realized having per-module `Deinit` was silly, since they'll like all be the same basic code (call `DataLoader_Reset` to close everything out, free everything, etc), so now only the `Init` functions are per-module, everything else is just an alias to the appropriate `DataLoader` function.

**Pull request merged**
