### PR TITLE
CMake: Use GNUInstallDirs & JoinPaths for installation

### PR DESCRIPTION
**Pull request by OPNA2608**
See [jtojnar/cmake-snips](https://github.com/jtojnar/cmake-snips) for more details on the how's and why's.

Include [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module to provide install directory variables according to GNU standards.

Add & include path joining module from the cmake-snips repo for constructing pkg-config paths. Module does not yet support Windows, so we fall back to the old paths there. (prolly not a big deal)

### CODE REVIEW

**Comment by ValleyBell** [comment]
Could you please apply the changes again to the current master branch and force-push your branch.

I'm sorry for the request, but I was in the middle of simplifying the pkg-config stuff when you opened the PR.

**Comment by OPNA2608** [comment]
I'll get to it on the weekend, no problem.

> Also, I'd prefer to not install the example programs by default, as they are not meant for daily use.

For context, this PR is to help with packaging libvgm for a package manager I'm using, which offers a high degree of configurability to the end-user. When building with the optional example programs enabled, then I as a user/developer would expect to find them in the (optional `bin`) output of that build, otherwise there wouldn't be any point in building them to begin with. I currently achieve this by manually copying over the enabled examples post-installation, but i figured installing them automatically if their associated CMake options are enabled would make sense.

If they're intentionally not being installed no matter their usefulness then I'll drop that part of the PR again.

**Comment by ValleyBell** [comment]
You're right - installing them just makes everything consistent. So let's just do that.

I can just set the `BUILD_TESTS` option to "off" by default instead.

**Comment by ValleyBell** [comment]
Sorry for the late merge.

I expected GitHub to send me a mail when new commits are pushed, but it somehow didn't do it. (maybe due to the force-push?)

**Pull request merged**
