### PR TITLE
add methods to access more kinds of track information

### PR DESCRIPTION
**Pull request by jpcima**
Adds song author, game, system, date, comment.

The tags remain unimplemented for dro files, although that adplug source code suggests there exist such a format. I don't know if there exist any samples of these around.

### CODE REVIEW

**Comment by ValleyBell** [comment]
I appreciate the effort, but I'd like to not have separate functions for every possible tag.  
I do admit that I have no concrete on how the API has to look like, but I'd rather go with a method like `GetSongTag(tag_name_or_ID)`.

Maybe we should chat a bit and discuss some ideas.

**Comment by jpcima** [comment]
>Maybe we should chat a bit and discuss some ideas.

Sure yes, I wrote here a summary of file information. It's taken from specifications as found here, and matched by similar purpose.
- [GD3](http://www.smspower.org/uploads/Music/gd3spec100.txt) (`*` have alternate japanese text found at N+1)
- [S98](https://github.com/Wohlstand/OPN2BankEditor/blob/37b19ef5a48cb0f20968ba5d83b8b00fa296d715/Specifications/s98spec3.txt#L275-L284)

| Tag                | VGM  | S98       |
|--------------------|------|-----------|
| Track name         | 0  * | title     |
| Game name          | 2  * | game      |
| System name        | 4  * | system    |
| Track author       | 6  * | artist    |
| Game Release Date  | 8    | year      |
| File author        | 9    | s98by     |
| Notes              | 10   | comment   |
| Genre              | -    | genre     |
| Copyright          | -    | copyright |

In order to offer a generic API to access all this, in a similar way as you describe, I think of:
- to identify each of these pieces of data to an enum known to `PlayerBase`. This one may be numbered after the GD3 specification.
- to have the virtual function `GetSongTag`, and for completeness `GetSongTagLocalized` which accepts as well a language code parameter

**Comment by superctr** [comment]
I suggest a single function returning a map or linked-list with two or three strings. The first string (key) can represent [vorbis tags](https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Vorbis.html), the second can be a language code (perhaps [BCP47](https://tools.ietf.org/rfc/bcp/bcp47.txt), e.g. en-US, ja-JP) and finally the tag contents.

**Comment by jprjr** [comment]
I'd keep it even simpler than that, I'd be perfectly happy with a function like:

```
const char *GetTag(enum TAG_ID, enum LANG_ID);
```

Where TAG_ID is a simple enum like `TITLE`, `GAME`, `SYSTEM`, etc, and LANG_ID is just `en` or `jp`. If the tag/lang combo doesn't exist (like if you request `GENRE` on a VGM) you just get `NULL`.

With appropriate prefixing of everything to avoid namespace collisions or whatever.

**Comment by superctr** [comment]
Well, there are some advantages with my approach, I think.

- By using vorbis tags it will be easier to integrate and use with other media players, and since we use a string instead of hardcoded enum it also makes the library backwards-compatible.

- By using a linked list or map instead of having to call the function for each tag it becomes easier to enumerate tags as you typically in a player application will want to fetch all tags at once anyway.

- libvgm could still provide a helper function to lookup a specific tag if we don't use a STL map, but I don't think we will need to abstract this.

**Comment by jprjr** [comment]
These are all good points, I think a linked list/map/array of pointers/etc would all work way better than my enum idea re: future-proofing.

**Comment by vampirefrog** [comment]
I'd like the same feature implemented, in any way that works and isn't too hard to implement.

**Comment by ValleyBell** [comment]
Made obsolete by #26

**Pull request closed without merging**
